# Generated by Django 2.0.1 on 2018-01-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=5)),
                ('author', models.CharField(max_length=35)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=65, unique=True)),
                ('content', models.TextField()),
                ('length', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('edit_time', models.DateTimeField()),
            ],
        ),
    ]
