# Generated by Django 2.0.1 on 2018-01-19 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180119_0057'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='softjob',
            table='SoftJob',
        ),
    ]
